name = "SunPy"
uuid = "d53ba2b8-6a4a-4633-896a-a050af4da271"
version = "1.0.0-DEV"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
OffsetArrays = "1"
PythonCall = "0.9"
julia = "1.10"
